namespace CoffeeNChill.Functions.DTO;

/// <summary>
/// Represents the information supplied by a customer when submitting a new
/// order to the CoffeeNChill order-processing endpoint.
/// </summary>
/// <remarks>
/// The order identifier and timestamp are generated by the application and
/// are therefore not included in the incoming request.
/// <para>Owner: Douglass Duncan — ST10473980</para>
/// </remarks>
public class OrderRequest
{
    /// <summary>
    /// Gets or sets the full name of the customer placing the order.
    /// </summary>
    /// <example>Jane Smith</example>
    public string CustomerName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the collection of menu-item SKUs selected by the customer.
    /// </summary>
    /// <example>COF-001, PAS-104</example>
    public List<string> SelectedItemSKUs { get; set; } = new();


}